<a href="https://colab.research.google.com/github/RasulAramian/Rasel.github.io/blob/MachinLearning/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np


# Creat array and matrix

In [23]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [24]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

# Shape

In [25]:
print(a.shape)
print(b.shape)

(4,)
(2, 2)


# Reshape


In [29]:
c = a.reshape((4,1))
c.shape

(4, 1)

In [33]:
d = a.reshape((2,-1,1))
d.shape

(2, 2, 1)

# Concatenate

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
c

array([5, 7, 9])

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
c

array([ 4, 10, 18])

# Broadcasting

In [40]:
c = np.array([10])
d = a + c

d

array([11, 12, 13])

In [41]:
e = a + 5
e

array([6, 7, 8])

# Slicing

In [43]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [44]:
b = a[2:7]
b

array([3, 4, 5, 6, 7])

In [45]:
b = a[2:7:2]
b

array([3, 5, 7])

In [47]:
b = a[a>3]
b

array([4, 5, 6, 7, 8])

# Functions

In [50]:
sum_a = np.sum(a)
sum_a

np.int64(36)

In [51]:
max_a = np.max(a)
max_a

np.int64(8)

In [52]:
min_a = np.min(a)
min_a

np.int64(1)

In [53]:
a = np.array([4, 2, 9, 6, 7, 3, 5])
b = np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 9])

In [58]:
a = np.random.randint(0, 10, (3,4))
a

array([[3, 5, 2, 0],
       [7, 2, 5, 5],
       [5, 0, 3, 9]])

In [66]:
a = np.random.uniform(0, 10, (3,4))
a

array([[0.49128751, 3.40357756, 9.17019605, 0.86331549],
       [4.09645465, 2.96778585, 9.83217878, 6.45828   ],
       [8.95413129, 8.80797577, 8.350982  , 3.69736411]])

In [65]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6])

# Normalize

In [69]:
mean_a = np.mean(a)
mean_a

np.float64(2.0)

In [70]:
std_a = np.std(a)
std_a

np.float64(0.816496580927726)

In [71]:
norm_a = (a - mean_a) / std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [72]:
np.mean(norm_a)

np.float64(0.0)

In [73]:
np.std(norm_a)

np.float64(0.9999999999999999)